module.exports = Object.freeze({
  PENDING: "PENDING",
  SUBMITTED: "SUBMITTED",
  LATE_SUBMISSION: "LATE SUBMISSION",
  NOT_SUBMITTED: "NOT SUBMITTED",
  values: ["PENDING", "SUBMITTED", "LATE SUBMISSION", "NOT SUBMITTED"],
});
